[application]
main-class = "apple.Main"

[dependencies]

[test-only-dependencies]
"org.junit.jupiter/junit-jupiter-api" = "5.8.2"

[bench-only-dependencies]
"org.openjdk.jmh/jmh-core" = "1.21"
"org.openjdk.jmh/jmh-generator-annprocess" = "1.21"