[application]
main-class = "dev.mccue.example.Main"

[dependencies]
"org.apache.commons/commons-lang3" = "3.12.0"
"org.apache.commons/commons-text" = "1.9"

[test-only-dependencies]
"org.junit.jupiter/junit-jupiter-api" = "5.8.2"

[runtime-only-dependencies]

[compile-only-dependencies]