[application]
main-class = "Main"

[dependencies]
"org.apache.commons/commons-lang3" = "3.12.0"
"org.apache.commons/commons-text" = "1.9"
"dev.mccue/magic-bean" = { version = "3.1.1", available-at = ["compile-time"]}

[test-only-dependencies]
"org.junit.jupiter/junit-jupiter-api" = "5.8.2"

[bench-only-dependencies]
"org.openjdk.jmh/jmh-core" = "1.21"
"org.openjdk.jmh/jmh-generator-annprocess" = { version = "1.21", available-at = ["compile-time"] }
